### PR TITLE
add 2024 theme (first in show/crescendo)

### PR DESCRIPTION
**Pull request by caburum**
FIRST's brand colors aren't very broad this year, so this is mostly green with a touch of blue. I tried to work in the pink, but it didn't really fit anywhere, though there is a hint in the [background](https://info.firstinspires.org/hubfs/first_in_show/texture2.webp).

msedge_2023-10-14-02-29-59-PM
msedge_2023-10-14-02-30-07-PM
msedge_2023-10-14-02-30-19-PM

### CODE REVIEW

**Comment by JL102** [comment]
LGTM! Nice work!

**Review by JL102 — APPROVED** [review]

**Comment by caburum** [comment]
I just check the main website, it seems that the colors updated, but the background and game logo (defined in layout.pug) seem to still be 2023 on both prod and test, though qa is fine. Did the assets get updated for those without the main code? I can't really think of any other explanation.

**Comment by JL102** [comment]
> I just check the main website, it seems that the colors updated, but the background and game logo (defined in layout.pug) seem to still be 2023 on both prod and test, though qa is fine. Did the assets get updated for those without the main code? I can't really think of any other explanation.

I don't remember updating the prod site code. I'll do a rebuild & static file sync & publish now, and see if that fixes it.

**Comment by JL102** [comment]
Fixed! _Maybe_ what happened was, when updating the static files to make the ™ logos appear on prod, I accidentally uploaded the 2024 theme css. Not sure though.

**Pull request merged**
